<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Laravel\Lumen\Auth\Authorizable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;

class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    function test()
    {
        $str = '{

"auto":[
        {
            "name":"指纹识别",
            "rename":"idsuo",
            "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"wifi检测",
            "rename":"wifi",
            "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"扬声器",
            "rename":"speaker",
            "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"麦克风",
            "rename":"microphone",
             "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"感应",
            "rename":"ganying",
             "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"照相机",
            "rename":"camera",
            "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"蓝牙",
            "rename":"bluetooth",
             "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"指南针",
            "rename":"compass",
             "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"gps检测",
            "rename":"gpsident",
            "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        },
        {
            "name":"通话功能",
            "rename":"telephone",
            "rule":{
                 "1":{
                    "suanfa":"+",
                    "value":"12"
		         }
                "2":{
                    "suanfa":"-",
                    "value":"34"
                 }   
            }
        }
    ],
    "shoudong":[
        {
            "id":31,
            "name":"屏幕外观",
            "sortName":"waiguan",
            "rename":"wanguan",
            "lists":[
                {
                    "name":"屏幕外观完好",
                    "validate":true,
                    "id":1,
                     "suanfa":"+",
                    "value":"0"
                },
                {
                    "name":"屏幕有明显划痕",
                    "validate":false,
                    "id":2,
                     "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"触摸屏失灵/破损",
                    "validate":false,
                    "id":3,
                    "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":32,
            "name":"屏幕显示",
            "sortName":"waiguan",
            "rename":"xianshi",
            "lists":[
                {
                    "name":"正常显示",
                    "validate":true,
                    "id":1,
                     "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"显示有亮点/色斑",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"显示液晶屏幕破裂/黑屏/漏夜",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":33,
            "name":"机身外观",
            "sortName":"waiguan",
            "rename":"jishen",
            "lists":[
                {
                    "name":"边框背板完好",
                    "validate":true,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"外壳有划痕/磕碰/掉漆",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"机身弯曲变形",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":34,
            "name":"进水和维修",
            "sortName":"gongneng",
            "rename":"weixiu",
            "lists":[
                {
                    "name":"无进水无维修",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"有进水/维修",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":35,
            "name":"机身外壳",
            "sortName":"gongneng",
            "rename":"waike",
            "lists":[
                {
                    "name":"边框背板完好",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"外壳有划痕/磕碰/掉漆",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"机身弯曲变形",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":36,
            "name":"保修情况",
            "sortName":"xinxi",
            "rename":"baoxiu",
            "lists":[
                {
                    "name":"一个月以上",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"一个月以内或过保",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "name":"网络制式渠道",
            "sortName":"xinxi",
            "rename":"qudao",
            "lists":[
                {
                    "name":"全网通",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"移动联通双4G",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"电信4G",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":37,
            "name":"颜色",
            "sortName":"xinxi",
            "rename":"yanse",
            "lists":[
                {
                    "name":"金",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"银",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"粉色",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":38,
            "name":"容量",
            "sortName":"xinxi",
            "rename":"rongliang",
            "lists":[
                {
                    "name":"8G",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"16G ",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"32G",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34",
                    
                },
                {
                    "name":"64G",
                    "validate":false,
                    "id":4,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"128G",
                    "validate":false,
                    "id":5,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        },
        {
            "id":39,
            "name":"维修拆机",
            "sortName":"gongneng",
            "rename":"chaiji",
            "lists":[
                {
                    "name":"无维修",
                    "validate":false,
                    "id":1,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"修过小部件（屏幕、按键） ",
                    "validate":false,
                    "id":2,
                      "suanfa":"-",
                    "value":"34"
                },
                {
                    "name":"修过主板 ",
                    "validate":false,
                    "id":3,
                      "suanfa":"-",
                    "value":"34"
                }
            ]
        }
    ]
}';
    }
}
